[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  SKIP_CACHE = "false"
  VITE_API_URL = "https://smoki-backend.onrender.com"
  VITE_CAMERA_API_URL = "https://smoki-backend-rpi.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
